# Generated by Django 5.1.3 on 2024-11-19 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PersonalInformationToValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_id', models.ImageField(upload_to='media/')),
                ('back_id', models.ImageField(upload_to='media/')),
                ('first_receipt', models.ImageField(upload_to='media/')),
                ('second_receipt', models.ImageField(upload_to='media/')),
                ('third_receipt', models.ImageField(upload_to='media/')),
                ('service_receipt', models.ImageField(upload_to='media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
