# Generated by Django 5.1.3 on 2024-11-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_guarantor',
            field=models.BooleanField(default=False),
        ),
    ]
