# Generated by Django 5.1.3 on 2024-11-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_month_duration', models.PositiveSmallIntegerField()),
                ('actual_month_duration', models.PositiveSmallIntegerField()),
                ('original_total_due', models.PositiveIntegerField()),
                ('actual_total_due', models.PositiveIntegerField()),
                ('interest_rate', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(choices=[('N', 'Normal'), ('D', 'Defaulter')], default='N', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_payment', models.PositiveIntegerField()),
                ('interest_payment', models.PositiveIntegerField()),
                ('principal_payment', models.PositiveIntegerField()),
                ('punitive_interest', models.PositiveIntegerField()),
                ('punitive_payment', models.PositiveIntegerField()),
                ('remaining_balance', models.PositiveIntegerField()),
                ('delayed', models.BooleanField(default=False)),
            ],
        ),
    ]
